export const GET_RISK_ASSESSMENT_QUESTIONS = 'GET_RISK_ASSESSMENT_QUESTIONS';
export const GET_HEALTH_ASSESSMENT_QUESTIONS = 'GET_HEALTH_ASSESSMENT_QUESTIONS';
export const GET_OFFENDER_ASSESSMENTS = 'GET_OFFENDER_ASSESSMENTS';
export const GET_VIPER_SCORES = 'GET_VIPER_SCORES';
export const ADD_VIPER_SCORE = 'ADD_VIPER_SCORE';
export const SELECT_OFFENDER = 'SELECT_OFFENDER';
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const CONFIRM_PRISONER = 'CONFIRM_PRISONER';
export const ADD_PRISONER = 'ADD_PRISONER';
export const SAVE_RISK_ASSESSMENT_ANSWER = 'SAVE_RISK_ASSESSMENT_ANSWER';
export const SAVE_HEALTHCARE_ANSWER = 'SAVE_HEALTHCARE_ANSWER';
export const COMPLETE_RISK_ASSESSMENT = 'COMPLETE_RISK_ASSESSMENT';
export const COMPLETE_HEALTH_ASSESSMENT = 'COMPLETE_HEALTH_ASSESSMENT';
export const HEALTHCARE_ANSWERS_COMPLETE = 'HEALTHCARE_ANSWERS_COMPLETE';


export const STORE_RISK_ASSESSMENT = 'STORE_RISK_ASSESSMENT';
export const START_RISK_ASSESSMENT = 'START_RISK_ASSESSMENT';
export const STORE_RISK_ASSESSMENT_ANSWER = 'STORE_RISK_ASSESSMENT_ANSWER';
export const STORE_RISK_ASSESSMENT_OUTCOME = 'STORE_RISK_ASSESSMENT_OUTCOME';
export const STORE_RISK_ASSESSMENT_REASONS = 'STORE_RISK_ASSESSMENT_REASONS';
