export const GET_RISK_ASSESSMENT_QUESTIONS = 'GET_RISK_ASSESSMENT_QUESTIONS';
export const GET_HEALTH_ASSESSMENT_QUESTIONS = 'GET_HEALTH_ASSESSMENT_QUESTIONS';
export const GET_OFFENDER_ASSESSMENTS = 'GET_OFFENDER_ASSESSMENTS';

export const SELECT_OFFENDER = 'SELECT_OFFENDER';

export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';

export const CONFIRM_PRISONER = 'CONFIRM_PRISONER';
export const ADD_PRISONER = 'ADD_PRISONER';

export const HEALTHCARE_ANSWERS_COMPLETE = 'HEALTHCARE_ANSWERS_COMPLETE';
export const RISK_ANSWERS_COMPLETE = 'RISK_ANSWERS_COMPLETE';

export const STORE_ASSESSMENT = 'STORE_ASSESSMENT';
export const START_ASSESSMENT = 'START_ASSESSMENT';
export const STORE_ASSESSMENT_ANSWER = 'STORE_ASSESSMENT_ANSWER';
export const STORE_ASSESSMENT_OUTCOME = 'STORE_ASSESSMENT_OUTCOME';
export const STORE_ASSESSMENT_REASONS = 'STORE_ASSESSMENT_REASONS';
