export default {
  SIGN_IN: '/sign-in',
  BEFORE_YOU_START: '/before-you-start',
  RISK_ASSESSMENT: '/risk-assessment',
  HEALTHCARE_ASSESSMENT: '/healthcare-assessment',
  ADMIN: '/admin',
  DASHBOARD: '/dashboard',
  PRISONER_PROFILE: '/offender-profile',
  ADD_OFFENDER: '/add-offender',
  CONFIRM_OFFENDER: '/confirm-offender',
  RISK_ASSESSMENT_SUMMARY: '/risk-assessment-summary',
  FEEDBACK: '/feedback',
  FEEDBACK_CONFIRMATION: '/feedback-confirmation',
  HEALTHCARE_SUMMARY: '/healthcare-summary',
  FULL_ASSESSMENT_COMPLETE: '/full-assessment-complete',
};
